### ISSUE TITLE
Not working with 2020.1.7

### ISSUE THREAD

**Issue by YanYas** [vvvv/VL.GStreamer#4]
Running HowTO Play a video file returns an immediate error:

```
Error: The type initializer for 'VL.Lib.GStreamer.Player' threw an exception.
   at VL.Lib.GStreamer.Player..ctor(VideoFormat format)
   at _HowTo_Play_a_Video_File_.Main.HowTo_Play_a_Video_FileApplication_EZdHkAKam7ONCvckCFeya4.<Create>g____TRACE__|2_0(<>c__DisplayClass2_0& ) in C:\Users\Igor\AppData\Local\vvvv\gamma\nugets\VL.GStreamer.1.0.24-gb632227dde\help\Video\HowTo Play a Video File.vl.cs:line 89
   at _HowTo_Play_a_Video_File_.Main.HowTo_Play_a_Video_FileApplication_EZdHkAKam7ONCvckCFeya4.Create(NodeContext Node_Context) in C:\Users\Igor\AppData\Local\vvvv\gamma\nugets\VL.GStreamer.1.0.24-gb632227dde\help\Video\HowTo Play a Video File.vl.cs:line 83
   at VL.Lang.Platforms.ImplicitEntryPointInstanceManager.RuntimeInstance.Step()
   at VL.Lang.Platforms.ImplicitEntryPointInstanceManager.StepInstances()
```
I tried changing the gstreamer installation but it doesn't seem to make a difference.

**Comment by tebjan** [comment]
this repo is a bit outdated, please try: https://github.com/vvvv/VL.MediaFoundation

**Comment by YanYas** [comment]
Thanks
